# Change these first
owner: edp163 # Your GitHub organization or username, where this repository lives
repo: supermoon-stat # The name of this repository

sites:
  - name: Supermoon Connector
    url: $SITE_URL_SUPERMOON_CONNECTOR
    method: GET
    headers:
      - "Authorization: Bearer $CLOUDFLARE_API_TOKEN"
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status":"healthy"'
  - name: mediakarir - FE kandidat
    url: $SITE_URL_MK_FE_KANDIDAT
  - name: mediakarir - FE 2
    url: $SITE_URL_MK_FE_INT
  - name: mediakarir - FE 3
    url: $SITE_URL_MK_FE_CRP
  - name: mediakarir API
    url: $SITE_URL_MK_BE

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: supermoon-stat.pages.dev
  # baseUrl: /supermoon-stat
  logoUrl: https://raw.githubusercontent.com/edp163/supermoon-stat/refs/heads/master/assets/teleskop.svg
  faviconSvg: https://raw.githubusercontent.com/edp163/supermoon-stat/refs/heads/master/assets/teleskop.svg
  name: Teleskop
  introTitle: "**Teleskop** merupakan layanan monitoring status server Supermoon."
  introMessage: Berikut adalah status koneksi **real-time** dari Supermoon platform. menggunakan GitHub Actions, Issues, dan CF Pages. 🔔 Notif telegram akan dikirim ketika koneksi Down.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: LUNA bot
  commitAuthorEmail: luna.bot@erapotensia.com

user-agent: luna-bot-agent

i18n:
  activeIncidents: Insiden Aktif
  incidentReport: "Laporan insiden #$NUMBER →"
  activeIncidentSummary: Dibuka pada $DATE dengan $POSTS postingan
  incidentTitle: Detail Insiden $NUMBER
  incidentDetails: Detail Insiden
  incidentFixed: Selesai
  incidentOngoing: Berlangsung
  incidentOpenedAt: Dibuka pada
  incidentClosedAt: Ditutup pada
  incidentViewOnGitHub: Lihat dan Berlangganan di GitHub
  incidentCommentSummary: Diposting pada $DATE oleh $AUTHOR
  incidentBack: ← Kembali ke semua insiden
  pastIncidents: Insiden Sebelumnya
  pastIncidentsResolved: Diselesaikan dalam $MINUTES menit dengan $POSTS postingan
  liveStatus: Status Langsung
  overallUptime: "Uptime keseluruhan: $UPTIME"
  overallUptimeTitle: Uptime keseluruhan
  averageResponseTime: "Waktu respons rata-rata: $TIMEms"
  averageResponseTimeTitle: Respons rata-rata
  sevelDayResponseTime: Waktu respons 7 hari
  responseTimeMs: Waktu respons (ms)
  ms: ms
  loading: Memuat...
  navGitHub: GitHub
  footer: Laman ini [open source]($REPO), didukung oleh [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Batas permintaan terlampaui
  rateLimitExceededIntro: Anda telah melampaui batas jumlah permintaan yang dapat dilakukan dalam satu jam, sehingga Anda harus menunggu sebelum mengakses situs web ini kembali. Sebagai alternatif, Anda dapat menambahkan Personal Access Token GitHub untuk terus menggunakan situs web ini.
  rateLimitExceededWhatDoesErrorMean: Apa arti dari kesalahan ini?
  rateLimitExceededErrorMeaning: Situs web ini menggunakan API GitHub untuk mengakses data real-time mengenai status situs web kami. Secara default, GitHub mengizinkan 60 permintaan per jam untuk setiap alamat IP, yang saat ini telah Anda habiskan.
  rateLimitExceededErrorHowCanFix: Bagaimana cara memperbaikinya?
  rateLimitExceededErrorFix: Anda dapat menunggu satu jam lagi dan batas alamat IP Anda akan dipulihkan. Sebagai alternatif, Anda dapat menambahkan Personal Access Token GitHub Anda, yang memberikan tambahan 5.000 permintaan per jam.
  rateLimitExceededGeneratePAT: Pelajari cara membuat Personal Access Token
  rateLimitExceededHasSet: Anda telah mengatur personal access token
  rateLimitExceededRemoveToken: Hapus token
  rateLimitExceededGitHubPAT: Personal Access Token GitHub
  rateLimitExceededCopyPastePAT: Salin dan tempel token Anda
  rateLimitExceededSaveToken: Simpan token
  errorTitle: Terjadi kesalahan
  errorIntro: Terjadi kesalahan saat mencoba mengambil detail status terbaru.
  errorText: Anda dapat mencoba lagi dalam beberapa saat.
  errorHome: Buka beranda
  pastScheduledMaintenance: Pemeliharaan Terjadwal Sebelumnya
  scheduledMaintenance: Pemeliharaan Terjadwal
  scheduledMaintenanceSummaryStarted: Dimulai pada $DATE selama $DURATION menit
  scheduledMaintenanceSummaryStarts: Dimulai pada $DATE selama $DURATION menit
  startedAt: Dimulai pada
  startsAt: Dimulai pada
  duration: Durasi
  durationMin: $DURATION menit
  incidentCompleted: Selesai
  incidentScheduled: Dijadwalkan
  duration24H: 24j
  duration7D: 7h
  duration30D: 30h
  duration1Y: 1th
  durationAll: semua
  locale: id-ID
  url: URL
  status: Status
  history: Riwayat
  responseTime: Waktu Respons
  uptime: Uptime
  up: 🟩 Normal
  degraded: 🟨 Terdegradasi
  down: 🟥 Down
  responseTimeGraphAlt: Grafik waktu respons
  responseTimeDay: Waktu respons 24 jam
  responseTimeWeek: Waktu respons 7 hari
  responseTimeMonth: Waktu respons 30 hari
  responseTimeYear: Waktu respons 1 tahun
  uptimeDay: Uptime 24 jam
  uptimeWeek: Uptime 7 hari
  uptimeMonth: Uptime 30 hari
  uptimeYear: Uptime 1 tahun
  liveStatusHtmlComment: <!--live status-->
  allSystemsOperational: 🟩 Semua sistem beroperasi dengan normal
  degradedPerformance: 🟨 Performa terdegradasi
  completeOutage: 🟥 Pemadaman total
  partialOutage: 🟧 Pemadaman sebagian
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
